name: Rust

on:
  push:

    branches: [ classification_experimental ]
  pull_request:
    branches: [ classification_experimental ]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


- name: Code Inspector GitHub action
  uses: codeinspectorio/github-action@v1


